export const LANDING = '/';
export const HOME = '/home';
export const LOGIN = '/login';
export const SIGNUP = '/signup';
export const USER_PROFILE = '/my_profile';
export const EDIT_PROFILE = '/my_profile/edit';
// export const EDIT_PROFILE = '/profile_edit';
export const PROPERTIES = '/properties';
export const ROOMIES = '/roomies';
export const ROOMIE_PROFILE = '/roomies/:username'